language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/
    - /^optimization\/.*$/

before_install:
  - |
    if [ "x$XDEBUG" != "xyes" ]; then
       phpenv config-rm xdebug.ini || true
    fi

install:
  - |
    if [[ "x$DEPS" == "xlowest" ]]; then
      travis_retry composer -n update --prefer-dist --prefer-lowest --prefer-stable --no-interaction $COMPOSER_ARGS;
    else
      travis_retry composer -n update --prefer-dist --no-interaction $COMPOSER_ARGS;
    fi

jobs:
  allow_failures:
    - php: nightly
    - stage: roave/no-leaks

  include:

    # All spec/unit tests for supported versions

    - stage: Tests
      php: 7.3
      script:
        - vendor/bin/phpspec run -fpretty -v
        - vendor/bin/phpunit

    - stage: Tests
      php: 7.2
      script:
          - vendor/bin/phpspec run -fpretty -v
          - vendor/bin/phpunit

    - stage: Tests
      php: 7.1
      script:
          - vendor/bin/phpspec run -fpretty -v
          - vendor/bin/phpunit

    - stage: Tests
      php: 7.1
      env: DEPS=lowest
      script:
          - vendor/bin/phpspec run -fpretty -v
          - vendor/bin/phpunit

    - stage: Tests
      php: nightly
      env: COMPOSER_ARGS=--ignore-platform-reqs
      script:
          - vendor/bin/phpspec run -fpretty -v
          - vendor/bin/phpunit

    # Tests for end of life versions

    - stage: Tests
      php: 7.0
      script:
        - vendor/bin/phpspec run -fpretty -v
        - vendor/bin/phpunit
        -
    - stage: Tests
      php: 5.6
      script:
        - vendor/bin/phpspec run -fpretty -v
        - vendor/bin/phpunit

    - stage: Tests
      php: 5.6
      env: DEPS=lowest
      script:
        - vendor/bin/phpspec run -fpretty -v
        - vendor/bin/phpunit

    - stage: Static analysis
      php: 7.1
      env: LABEL=phpstan
      script:
        - composer require --dev phpstan/phpstan phpstan/phpstan-phpunit
        - composer phpstan

    # [Experimental ] No-leaks stage
    # This stage will fail for now, and it's fine
    # It's an attempt to get roave/no-leaks works with prophecy
    # See https://github.com/Roave/no-leaks/pull/14

    - stage: roave/no-leaks
      php: 7.3
      env: XDEBUG=yes LABEL="experimental - can fail"
      script:
          - composer require --dev roave/no-leaks
          - vendor/bin/roave-no-leaks
